// Generated by scripts/research-desk.ts. Review, then copy to content/planks.ts.
import type { Plank } from "@/content/schema";

export const PLANKS: Plank[] = [
  {
    "id": "dnc-2024-3",
    "party": "D",
    "topic": "Defense and foreign policy",
    "statement": "Place further limits on foreign ownership of farmland in the United States.",
    "quote": "And we will look to further limit foreign ownership of U.S. farmland to protect our food supply and national security.",
    "source": {
      "doc": "dnc-2024",
      "section": "AGRICULTURE",
      "url": "https://www.presidency.ucsb.edu/documents/2024-democratic-party-platform"
    },
    "counterType": true
  },
  {
    "id": "dnc-2024-4",
    "party": "D",
    "topic": "Jobs and trade",
    "statement": "Raise tariffs on Chinese steel, aluminum, semiconductors, electric vehicles, batteries, solar cells and medical products.",
    "quote": "strategically increasing tariffs on a variety of products such as steel and aluminum, semiconductors, electric vehicles, batteries, critical minerals, solar cells, ship-to-shore cranes, and medical products.",
    "source": {
      "doc": "dnc-2024",
      "section": "CHINA",
      "url": "https://www.presidency.ucsb.edu/documents/2024-democratic-party-platform"
    },
    "counterType": true
  },
  {
    "id": "dnc-2024-5",
    "party": "D",
    "topic": "Immigration",
    "statement": "Give the president emergency power to expel unlawful border crossers and pause most asylum processing during surges.",
    "quote": "When the system is overwhelmed, the President should have emergency authority to expel migrants who are crossing unlawfully and stop processing asylum claims except for those using a safe and orderly process at Ports of Entry.",
    "source": {
      "doc": "dnc-2024",
      "section": "Temporary Emergency Authority to Shut Down the Border",
      "url": "https://www.presidency.ucsb.edu/documents/2024-democratic-party-platform"
    },
    "counterType": true
  },
  {
    "id": "dnc-2024-6",
    "party": "D",
    "topic": "Crime, policing and drugs",
    "statement": "Fund 100,000 additional police officers and $5 billion for community violence intervention programs.",
    "quote": "That includes funding 100,000 additional police officers for accountable community policing and $5 billion in community violence intervention",
    "source": {
      "doc": "dnc-2024",
      "section": "POLICING & PUBLIC SAFETY",
      "url": "https://www.presidency.ucsb.edu/documents/2024-democratic-party-platform"
    },
    "counterType": true
  },
  {
    "id": "dnc-2024-7",
    "party": "D",
    "topic": "Energy and climate",
    "statement": "Allow sales of cheaper E15 ethanol-blended gasoline every summer to lower prices at the pump.",
    "quote": "it is lowering gas prices by up to 25 cents per gallon more in certain markets, particularly in the Midwest, by making cheaper, E15 ethanol-blended gasoline available each summer.",
    "source": {
      "doc": "dnc-2024",
      "section": "GAS & GROCERIES",
      "url": "https://www.presidency.ucsb.edu/documents/2024-democratic-party-platform"
    },
    "counterType": true
  },
  {
    "id": "dnc-2024-8",
    "party": "D",
    "topic": "Defense and foreign policy",
    "statement": "Modernize the land, sea and air legs of the U.S. nuclear weapons arsenal.",
    "quote": "maintained a commitment to modernize and recapitalize the nuclear triad as the bedrock of deterrence",
    "source": {
      "doc": "dnc-2024",
      "section": "STRONGEST MILITARY IN THE WORLD",
      "url": "https://www.presidency.ucsb.edu/documents/2024-democratic-party-platform"
    },
    "counterType": true
  },
  {
    "id": "dnc-2024-1",
    "party": "D",
    "topic": "Taxes and spending",
    "statement": "Require billionaires to pay a minimum federal income tax rate of 25 percent.",
    "quote": "Democrats will make billionaires pay a minimum income tax rate of 25 percent, raising $500 billion in 10 years.",
    "source": {
      "doc": "dnc-2024",
      "section": "MAKING THE WEALTHY & BIG CORPORATIONS PAY THEIR FAIR SHARE",
      "url": "https://www.presidency.ucsb.edu/documents/2024-democratic-party-platform"
    },
    "counterType": false
  },
  {
    "id": "dnc-2024-2",
    "party": "D",
    "topic": "Jobs and trade",
    "statement": "Raise the federal minimum wage to at least $15 an hour.",
    "quote": "We'll work to finally raise the federal minimum wage to at least $15-an-hour.",
    "source": {
      "doc": "dnc-2024",
      "section": "FIGHTING POVERTY",
      "url": "https://www.presidency.ucsb.edu/documents/2024-democratic-party-platform"
    },
    "counterType": false
  },
  {
    "id": "dnc-2024-9",
    "party": "D",
    "topic": "Guns",
    "statement": "Reinstate a federal ban on assault weapons and high-capacity magazines.",
    "quote": "We will once again ban assault weapons and high-capacity magazines.",
    "source": {
      "doc": "dnc-2024",
      "section": "GUN SAFETY",
      "url": "https://www.presidency.ucsb.edu/documents/2024-democratic-party-platform"
    },
    "counterType": false
  },
  {
    "id": "dnc-2024-10",
    "party": "D",
    "topic": "Health care",
    "statement": "Cap insulin costs at $35 a month for all Americans, not just Medicare enrollees.",
    "quote": "Now, we'll fight to expand that $35 cap to cover everyone, saving millions of Americans with diabetes nearly $1,000 a year.",
    "source": {
      "doc": "dnc-2024",
      "section": "Prescription Drugs",
      "url": "https://www.presidency.ucsb.edu/documents/2024-democratic-party-platform"
    },
    "counterType": false
  },
  {
    "id": "dnc-2024-11",
    "party": "D",
    "topic": "Retirement",
    "statement": "Expand traditional Medicare to cover dental, vision and hearing services.",
    "quote": "We'll look to expand traditional Medicare coverage to include dental, vision, and hearing services",
    "source": {
      "doc": "dnc-2024",
      "section": "SOCIAL SECURITY, PENSIONS, & MEDICARE",
      "url": "https://www.presidency.ucsb.edu/documents/2024-democratic-party-platform"
    },
    "counterType": false
  },
  {
    "id": "dnc-2024-12",
    "party": "D",
    "topic": "Education",
    "statement": "Provide free universal preschool for every four-year-old in the country.",
    "quote": "That's why Democrats will provide free, universal preschool for four-year olds, saving the families of 5 million children $13,000 a year.",
    "source": {
      "doc": "dnc-2024",
      "section": "EDUCATION",
      "url": "https://www.presidency.ucsb.edu/documents/2024-democratic-party-platform"
    },
    "counterType": false
  },
  {
    "id": "dnc-2024-13",
    "party": "D",
    "topic": "Elections and government",
    "statement": "Pass a constitutional amendment banning all private financing of federal election campaigns.",
    "quote": "We will keep super PACs wholly independent of campaigns and parties and pass a constitutional amendment that will ban all private financing from federal elections.",
    "source": {
      "doc": "dnc-2024",
      "section": "STOPPING THE INFLUENCE OF SPECIAL INTERESTS",
      "url": "https://www.presidency.ucsb.edu/documents/2024-democratic-party-platform"
    },
    "counterType": false
  },
  {
    "id": "dnc-2024-14",
    "party": "D",
    "topic": "Rights and speech",
    "statement": "Pass a national law restoring the abortion protections that existed under Roe v. Wade.",
    "quote": "With a Democratic Congress, we will pass national legislation to make Roe the law of the land again.",
    "source": {
      "doc": "dnc-2024",
      "section": "REPRODUCTIVE FREEDOM",
      "url": "https://www.presidency.ucsb.edu/documents/2024-democratic-party-platform"
    },
    "counterType": false
  },
  {
    "id": "dnc-2024-15",
    "party": "D",
    "topic": "Crime, policing and drugs",
    "statement": "Expunge federal criminal records for people convicted only of marijuana offenses.",
    "quote": "Democrats will take action to expunge federal marijuana-only convictions.",
    "source": {
      "doc": "dnc-2024",
      "section": "CRIMINAL JUSTICE",
      "url": "https://www.presidency.ucsb.edu/documents/2024-democratic-party-platform"
    },
    "counterType": false
  },
  {
    "id": "rnc-2024-6",
    "party": "R",
    "topic": "Jobs and trade",
    "statement": "Bar companies that move jobs overseas from receiving federal government contracts.",
    "quote": "Republicans will strengthen Buy American and Hire American Policies, banning companies that outsource jobs from doing business with the Federal Government.",
    "source": {
      "doc": "rnc-2024",
      "section": "5. Buy American and Hire American",
      "url": "https://www.presidency.ucsb.edu/documents/2024-republican-party-platform"
    },
    "counterType": true
  },
  {
    "id": "rnc-2024-7",
    "party": "R",
    "topic": "Retirement",
    "statement": "Rule out any cuts to Social Security or Medicare, including raising the retirement age.",
    "quote": "FIGHT FOR AND PROTECT SOCIAL SECURITY AND MEDICARE WITH NO CUTS, INCLUDING NO CHANGES TO THE RETIREMENT AGE",
    "source": {
      "doc": "rnc-2024",
      "section": "PREAMBLE",
      "url": "https://www.presidency.ucsb.edu/documents/2024-republican-party-platform"
    },
    "counterType": true
  },
  {
    "id": "rnc-2024-8",
    "party": "R",
    "topic": "Retirement",
    "statement": "Create tax credits for unpaid family caregivers and shift senior care funding toward at-home care.",
    "quote": "Republicans will shift resources back to at-home Senior Care, overturn disincentives that lead to Care Worker shortages, and support unpaid Family Caregivers through Tax Credits and reduced red tape.",
    "source": {
      "doc": "rnc-2024",
      "section": "4. Protect Care at Home for the Elderly",
      "url": "https://www.presidency.ucsb.edu/documents/2024-republican-party-platform"
    },
    "counterType": true
  },
  {
    "id": "rnc-2024-9",
    "party": "R",
    "topic": "Health care",
    "statement": "Support policies that expand access to birth control, IVF, and prenatal care.",
    "quote": "supporting mothers and policies that advance Prenatal Care, access to Birth Control, and IVF (fertility treatments).",
    "source": {
      "doc": "rnc-2024",
      "section": "4. Republicans Will Protect and Defend a Vote of the People, from within the States, on the Issue of Life",
      "url": "https://www.presidency.ucsb.edu/documents/2024-republican-party-platform"
    },
    "counterType": true
  },
  {
    "id": "rnc-2024-1",
    "party": "R",
    "topic": "Immigration",
    "statement": "Complete the southern border wall and reassign large portions of federal law enforcement to immigration enforcement.",
    "quote": "We will complete the Border Wall, shift massive portions of Federal Law Enforcement to Immigration Enforcement, and use advanced technology to monitor and secure the Border.",
    "source": {
      "doc": "rnc-2024",
      "section": "1. Secure the Border",
      "url": "https://www.presidency.ucsb.edu/documents/2024-republican-party-platform"
    },
    "counterType": false
  },
  {
    "id": "rnc-2024-2",
    "party": "R",
    "topic": "Immigration",
    "statement": "Cut federal funding to cities and counties that refuse to transfer arrested immigrants to federal immigration authorities.",
    "quote": "Republicans will cut federal Funding to sanctuary jurisdictions that release dangerous Illegal Alien criminals onto our streets, rather than handing them over to ICE.",
    "source": {
      "doc": "rnc-2024",
      "section": "5. Stop Sanctuary Cities",
      "url": "https://www.presidency.ucsb.edu/documents/2024-republican-party-platform"
    },
    "counterType": false
  },
  {
    "id": "rnc-2024-3",
    "party": "R",
    "topic": "Taxes and spending",
    "statement": "Eliminate federal income taxes on tips for restaurant and hospitality workers.",
    "quote": "We will eliminate Taxes on Tips for millions of Restaurant and Hospitality Workers, and pursue additional Tax Cuts.",
    "source": {
      "doc": "rnc-2024",
      "section": "2. Make Trump Tax Cuts Permanent and No Tax on Tips",
      "url": "https://www.presidency.ucsb.edu/documents/2024-republican-party-platform"
    },
    "counterType": false
  },
  {
    "id": "rnc-2024-4",
    "party": "R",
    "topic": "Taxes and spending",
    "statement": "Make permanent the Tax Cuts and Jobs Act provisions, including the doubled standard deduction.",
    "quote": "Republicans will make permanent the provisions of the Trump Tax Cuts and Jobs Act that doubled the standard deduction, expanded the Child Tax Credit, and spurred Economic Growth for all Americans.",
    "source": {
      "doc": "rnc-2024",
      "section": "2. Make Trump Tax Cuts Permanent and No Tax on Tips",
      "url": "https://www.presidency.ucsb.edu/documents/2024-republican-party-platform"
    },
    "counterType": false
  },
  {
    "id": "rnc-2024-5",
    "party": "R",
    "topic": "Jobs and trade",
    "statement": "Impose baseline tariffs on foreign-made goods and match the tariffs other countries charge on U.S. exports.",
    "quote": "Republicans will support baseline Tariffs on Foreign-made goods, pass the Trump Reciprocal Trade Act, and respond to unfair Trading practices.",
    "source": {
      "doc": "rnc-2024",
      "section": "1. Rebalance Trade",
      "url": "https://www.presidency.ucsb.edu/documents/2024-republican-party-platform"
    },
    "counterType": false
  },
  {
    "id": "rnc-2024-10",
    "party": "R",
    "topic": "Energy and climate",
    "statement": "Cancel federal electric vehicle mandates and ban the import of Chinese-made vehicles.",
    "quote": "Republicans will revive the U.S. Auto Industry by reversing harmful Regulations, canceling Biden's Electric Vehicle and other Mandates, and preventing the importation of Chinese vehicles.",
    "source": {
      "doc": "rnc-2024",
      "section": "3. Save the American Auto Industry",
      "url": "https://www.presidency.ucsb.edu/documents/2024-republican-party-platform"
    },
    "counterType": false
  },
  {
    "id": "rnc-2024-11",
    "party": "R",
    "topic": "Education",
    "statement": "Close the federal Department of Education and return control of schooling to the states.",
    "quote": "We are going to close the Department of Education in Washington, D.C. and send it back to the States, where it belongs, and let the States run our educational system as it should be run.",
    "source": {
      "doc": "rnc-2024",
      "section": "9. Return Education to the States",
      "url": "https://www.presidency.ucsb.edu/documents/2024-republican-party-platform"
    },
    "counterType": false
  },
  {
    "id": "rnc-2024-12",
    "party": "R",
    "topic": "Crime, policing and drugs",
    "statement": "Deploy the Navy to board and inspect ships in regional waters for fentanyl and its precursors.",
    "quote": "We will deploy the U.S. Navy to impose a full Fentanyl Blockade on the waters of our Region—boarding and inspecting ships to look for fentanyl and fentanyl precursors.",
    "source": {
      "doc": "rnc-2024",
      "section": "1. Secure the Border",
      "url": "https://www.presidency.ucsb.edu/documents/2024-republican-party-platform"
    },
    "counterType": false
  },
  {
    "id": "rnc-2024-13",
    "party": "R",
    "topic": "Defense and foreign policy",
    "statement": "Build a nationwide missile defense shield and raise pay for military service members.",
    "quote": "We will invest in cutting-edge research and advanced technologies, including an Iron Dome Missile Defense Shield, support our Troops with higher pay",
    "source": {
      "doc": "rnc-2024",
      "section": "2. Modernize the Military",
      "url": "https://www.presidency.ucsb.edu/documents/2024-republican-party-platform"
    },
    "counterType": false
  },
  {
    "id": "rnc-2024-14",
    "party": "R",
    "topic": "Elections and government",
    "statement": "Require voter ID, paper ballots, and proof of citizenship to vote in elections.",
    "quote": "We will implement measures to secure our Elections, including Voter ID, highly sophisticated paper ballots, proof of Citizenship, and same day Voting.",
    "source": {
      "doc": "rnc-2024",
      "section": "6. Republicans Will Ensure Election Integrity",
      "url": "https://www.presidency.ucsb.edu/documents/2024-republican-party-platform"
    },
    "counterType": false
  },
  {
    "id": "rnc-2024-15",
    "party": "R",
    "topic": "Rights and speech",
    "statement": "Ban federal agencies from working with outside groups to remove lawful speech and defund institutions that do so.",
    "quote": "We will ban the Federal Government from colluding with anyone to censor Lawful Speech, defund institutions engaged in censorship, and hold accountable all bureaucrats involved with illegal censoring.",
    "source": {
      "doc": "rnc-2024",
      "section": "2. Republicans Will Dismantle Censorship & Protect Free Speech",
      "url": "https://www.presidency.ucsb.edu/documents/2024-republican-party-platform"
    },
    "counterType": false
  },
  {
    "id": "lp-2024-3",
    "party": "L",
    "topic": "Crime, policing and drugs",
    "statement": "Abolish qualified immunity so police and prosecutors can be sued for misconduct.",
    "quote": "we support the abolition of qualified immunity so that law enforcement and prosecutors would be held legally accountable for misconduct that leads to wrongful convictions or other acts of injustice.",
    "source": {
      "doc": "lp-2024",
      "section": "1.7 Crime and Justice",
      "url": "https://lp.org/platform/"
    },
    "counterType": true
  },
  {
    "id": "lp-2024-4",
    "party": "L",
    "topic": "Crime, policing and drugs",
    "statement": "End the use of the death penalty by federal and state governments.",
    "quote": "We oppose the administration of the death penalty by the state.",
    "source": {
      "doc": "lp-2024",
      "section": "1.8 Death Penalty",
      "url": "https://lp.org/platform/"
    },
    "counterType": true
  },
  {
    "id": "lp-2024-12",
    "party": "L",
    "topic": "Education",
    "statement": "End federal student loan guarantees and the special treatment of student loan debt in bankruptcy.",
    "quote": "We support ending federal student loan guarantees and special treatment of student loan debt in bankruptcy proceedings.",
    "source": {
      "doc": "lp-2024",
      "section": "2.7 Money and Financial Markets",
      "url": "https://lp.org/platform/"
    },
    "counterType": true
  },
  {
    "id": "lp-2024-15",
    "party": "L",
    "topic": "Rights and speech",
    "statement": "Grant marriage licenses to all consenting adults who apply until government stops licensing marriage entirely.",
    "quote": "Until such time as the government stops its illegitimate practice of marriage licensing, such licenses must be granted to all consenting adults who apply.",
    "source": {
      "doc": "lp-2024",
      "section": "1.4 Personal Relationships",
      "url": "https://lp.org/platform/"
    },
    "counterType": true
  },
  {
    "id": "lp-2024-1",
    "party": "L",
    "topic": "Taxes and spending",
    "statement": "Repeal the federal income tax and abolish the Internal Revenue Service.",
    "quote": "we call for the repeal of the income tax, the abolishment of the Internal Revenue Service and all federal programs and services not required under the U.S. Constitution.",
    "source": {
      "doc": "lp-2024",
      "section": "2.4 Government Finance and Spending",
      "url": "https://lp.org/platform/"
    },
    "counterType": false
  },
  {
    "id": "lp-2024-2",
    "party": "L",
    "topic": "Retirement",
    "statement": "Phase out the current Social Security system and replace it with a private, voluntary system.",
    "quote": "Libertarians would phase out the current government-sponsored Social Security system and transition to a private voluntary system.",
    "source": {
      "doc": "lp-2024",
      "section": "2.14 Retirement and Income Security",
      "url": "https://lp.org/platform/"
    },
    "counterType": false
  },
  {
    "id": "lp-2024-5",
    "party": "L",
    "topic": "Crime, policing and drugs",
    "statement": "Repeal laws against gambling, drug use, and consensual paid sex between adults.",
    "quote": "we favor the repeal of all laws creating “crimes” without victims, such as gambling, the use of drugs for medicinal or recreational purposes, and consensual transactions involving sexual services.",
    "source": {
      "doc": "lp-2024",
      "section": "1.7 Crime and Justice",
      "url": "https://lp.org/platform/"
    },
    "counterType": false
  },
  {
    "id": "lp-2024-6",
    "party": "L",
    "topic": "Guns",
    "statement": "Repeal all laws restricting, registering, or monitoring the ownership, manufacture, or transfer of firearms.",
    "quote": "We oppose all laws at any level of government restricting, registering, or monitoring the ownership, manufacture, or transfer of firearms, ammunition, or firearm accessories.",
    "source": {
      "doc": "lp-2024",
      "section": "1.9 Self-Defense",
      "url": "https://lp.org/platform/"
    },
    "counterType": false
  },
  {
    "id": "lp-2024-7",
    "party": "L",
    "topic": "Immigration",
    "statement": "Allow unrestricted movement of people and capital across national borders.",
    "quote": "Economic freedom demands the unrestricted movement of human as well as financial capital across national borders.",
    "source": {
      "doc": "lp-2024",
      "section": "3.4 Free Trade and Migration",
      "url": "https://lp.org/platform/"
    },
    "counterType": false
  },
  {
    "id": "lp-2024-8",
    "party": "L",
    "topic": "Defense and foreign policy",
    "statement": "End U.S. military and economic aid abroad, tariffs, economic sanctions, and regime change efforts.",
    "quote": "We would end the current U.S. government policies of foreign intervention including military and economic aid; tariffs; economic sanctions; and regime change.",
    "source": {
      "doc": "lp-2024",
      "section": "3.3 International Affairs",
      "url": "https://lp.org/platform/"
    },
    "counterType": false
  },
  {
    "id": "lp-2024-9",
    "party": "L",
    "topic": "Jobs and trade",
    "statement": "Repeal occupational licensing laws that restrict who may work in a trade or profession.",
    "quote": "we oppose occupational and other licensing laws that infringe on this right or treat it as a state-granted privilege.",
    "source": {
      "doc": "lp-2024",
      "section": "2.9 Licensing",
      "url": "https://lp.org/platform/"
    },
    "counterType": false
  },
  {
    "id": "lp-2024-10",
    "party": "L",
    "topic": "Energy and climate",
    "statement": "End government subsidies for every form of energy production.",
    "quote": "While energy is needed to fuel a modern society, government should not be subsidizing any particular form of energy.",
    "source": {
      "doc": "lp-2024",
      "section": "2.3 Energy and Resources",
      "url": "https://lp.org/platform/"
    },
    "counterType": false
  },
  {
    "id": "lp-2024-11",
    "party": "L",
    "topic": "Education",
    "statement": "Give parents control over all public funds spent on their children's education.",
    "quote": "Parents should have control of and responsibility for all funds expended for their children’s education.",
    "source": {
      "doc": "lp-2024",
      "section": "2.12 Education",
      "url": "https://lp.org/platform/"
    },
    "counterType": false
  },
  {
    "id": "lp-2024-13",
    "party": "L",
    "topic": "Health care",
    "statement": "Bar government from mandating or restricting voluntary access to medical treatments, including vaccines.",
    "quote": "We oppose governments either mandating, or restricting voluntary access to, medical treatments or procedures including vaccines.",
    "source": {
      "doc": "lp-2024",
      "section": "2.13 Health Care",
      "url": "https://lp.org/platform/"
    },
    "counterType": false
  },
  {
    "id": "lp-2024-14",
    "party": "L",
    "topic": "Elections and government",
    "statement": "Adopt proportional representation and alternative voting systems, and add a none-of-the-above option to all ballots.",
    "quote": "We support election systems that are more representative of the electorate at the federal, state, and local levels, such as proportional representation, alternative voting systems, and explicit inclusion of “none of the above” on all ballots.",
    "source": {
      "doc": "lp-2024",
      "section": "3.6 Representative Government",
      "url": "https://lp.org/platform/"
    },
    "counterType": false
  }
];
