// The Research Desk: asks Claude to draft cards from each party platform, checks
// every card, and writes the drafts for review. Run with `npm run desk`.
//
//   --party X   rerun one platform (D, R or L) and replace only its entries
//   --refresh   fetch the platform pages again instead of reading the cache

import Anthropic from "@anthropic-ai/sdk";
import { betaZodOutputFormat } from "@anthropic-ai/sdk/helpers/beta/zod";
import { existsSync, mkdirSync, readFileSync, writeFileSync } from "node:fs";
import { CandidatesSchema, PartySchema, type Party } from "@/content/schema";
import { checkCandidates, toDraftPlanks, type CheckCounts, type CheckedCandidate } from "./lib/candidates";
import { PLATFORMS } from "./lib/platforms";
import { getSource } from "./lib/sources";

const MODEL = "claude-opus-5-5";
const CANDIDATES_PATH = "research/candidates.json";
const DRAFT_PATH = "research/planks.draft.ts";

type PlatformResult = { model: string; counts: CheckCounts; cards: CheckedCandidate[] };
type CandidatesFile = Partial<Record<Party, PlatformResult>>;

async function main() {
  const args = process.argv.slice(2);
  const partyArg = args.includes("--party") ? args[args.indexOf("--party") + 1] : undefined;
  const parties: Party[] = partyArg ? [PartySchema.parse(partyArg)] : ["D", "R", "L"];
  const refresh = args.includes("--refresh");

  const client = new Anthropic();
  const system = readFileSync("scripts/prompts/desk.md", "utf8");

  // The three platforms run in parallel. One failing doesn't stop the others.
  const settled = await Promise.allSettled(
    parties.map((party) => runPlatform(client, system, party, refresh)),
  );

  const file: CandidatesFile = existsSync(CANDIDATES_PATH)
    ? JSON.parse(readFileSync(CANDIDATES_PATH, "utf8"))
    : {};
  let failed = false;
  settled.forEach((outcome, i) => {
    const party = parties[i];
    if (outcome.status === "rejected") {
      failed = true;
      console.error(`${party}: FAILED: ${outcome.reason}`);
      return;
    }
    const { counts, model } = outcome.value;
    file[party] = outcome.value;
    console.log(
      `${party}: ${counts.proposed} proposed · ${counts.passed} quote ok · ${counts.flagged} flagged · ${model}`,
    );
  });

  mkdirSync("research", { recursive: true });
  writeFileSync(CANDIDATES_PATH, JSON.stringify(file, null, 2) + "\n");
  const allCards = Object.values(file).flatMap((result) => result.cards);
  writeFileSync(DRAFT_PATH, draftFile(toDraftPlanks(allCards)));

  if (failed) process.exit(1);
}

async function runPlatform(
  client: Anthropic,
  system: string,
  party: Party,
  refresh: boolean,
): Promise<PlatformResult> {
  const sourceText = await getSource(party, refresh);

  // One retry, at lower effort, when the output is cut off or doesn't parse.
  for (const effort of ["high", "medium"] as const) {
    let response;
    try {
      response = await client.beta.messages.parse({
        model: MODEL,
        // Stay under 21,333, or the SDK demands streaming. Thinking counts too.
        max_tokens: 20000,
        betas: ["server-side-fallback-2026-07-01"],
        fallbacks: "default",
        output_config: { effort, format: betaZodOutputFormat(CandidatesSchema) },
        system,
        messages: [{ role: "user", content: `This is ${PLATFORMS[party].name}.\n\n${sourceText}` }],
      });
    } catch (error) {
      // HTTP and connection errors are real failures; the SDK has already
      // retried them. Any other SDK error here means parse() couldn't read the
      // output: cut off at max_tokens, or not matching the schema.
      if (error instanceof Anthropic.APIError || !(error instanceof Anthropic.AnthropicError)) throw error;
      console.warn(`${party}: output unusable at effort ${effort}: ${error.message}`);
      continue;
    }

    const { input_tokens, output_tokens } = response.usage;
    console.log(
      `${party}: ${response.model} at effort ${effort}, stop_reason ${response.stop_reason}, ${input_tokens} in / ${output_tokens} out`,
    );

    // Check the stop reason before reading the output.
    if (response.stop_reason === "refusal") {
      // The fallback model has already had its turn, so there's no one left to ask.
      throw new Error(`refused: ${JSON.stringify(response.stop_details)}`);
    }
    if (response.stop_reason === "max_tokens" || !response.parsed_output) {
      console.warn(`${party}: no usable output at effort ${effort}`);
      continue;
    }

    // The party comes from the platform, never from Claude.
    const { cards, counts } = checkCandidates(party, response.parsed_output.cards, sourceText);
    return { model: response.model, counts, cards };
  }
  throw new Error("no usable output at effort high or medium");
}

function draftFile(planks: ReturnType<typeof toDraftPlanks>): string {
  return [
    "// Generated by scripts/research-desk.ts. Review, then copy to content/planks.ts.",
    'import type { Plank } from "@/content/schema";',
    "",
    `export const PLANKS: Plank[] = ${JSON.stringify(planks, null, 2)};`,
    "",
  ].join("\n");
}

main().catch((error) => {
  console.error(error);
  process.exit(1);
});
